### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by arcanestarme** [RedDuckss/csms#1]
Hello! I got this issue:
```
/root/csms/server.js:20
app.get('/api/v1/pickup/:difficulty', async (request, response) => {
                                            ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
How do I fix this?

**Comment by silasary** [comment]
Update to the latest version of Node.

**Comment by jonbarrow** [comment]
The cause of that issue is your outdated version of Node, as @silasary said. The latest version of Node to support async/await is 7.6. The latest version is 9.7.1 and the LTS is 8.9.4, so you seem to be very outdated if async/await isn't supported in your version.

However this repo is not meant to be used. It has been abandoned and the knowledge gained while working on this repo has given birth to a new project, called Pretendo, which aims to serve replacement servers for the WiiU and 3DS/2DS. You can find this new project here https://github.com/PretendoNetwork/Pretendo as it is much more updated than the server here, and is actually working (to an extent)
